---

version: "3"

services:
  mail-service-task:
    #build:
    #  context: .
    #  dockerfile: Dockerfile
    image:
      mail-service-task:latest
    ports:
      - 3002:3000
      - 4002:4000
    depends_on:
      - mongo-db

  mongo-db-task:
    image:
      mongo:latest
    volumes:
      - ./configs/mongod.conf:/etc/mongod.conf
    ports:
      - 27017:27017
    command: --config /etc/mongod.conf
  
  mail-service-auth:
    #build:
    #  context: .
    #  dockerfile: ../mail-service-auth/Dockerfile
    image:
      mail-service-auth:latest
    ports:
      - 3001:3000
      - 4001:4000
#    depends_on:
#      - mongo-db

  mail-service-analytics:
    image:
      mail-service-analytics:latest
    ports:
      - 3003:3000
      - 4003:4000
    depends_on:
      postgres-db-analytics:
        condition: service_healthy
  
  postgres-db-analytics:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
    ports:
      - 5432:5432
    volumes:
      - ./scripts/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
