// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.13.0
// source: proto/mail-service-auth-grpc.proto

package authgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AuthGrpcClient is the client API for AuthGrpc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthGrpcClient interface {
	Validate(ctx context.Context, in *TokenPair, opts ...grpc.CallOption) (*AuthResponse, error)
}

type authGrpcClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthGrpcClient(cc grpc.ClientConnInterface) AuthGrpcClient {
	return &authGrpcClient{cc}
}

func (c *authGrpcClient) Validate(ctx context.Context, in *TokenPair, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := c.cc.Invoke(ctx, "/authgrpc.AuthGrpc/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthGrpcServer is the server API for AuthGrpc service.
// All implementations must embed UnimplementedAuthGrpcServer
// for forward compatibility
type AuthGrpcServer interface {
	Validate(context.Context, *TokenPair) (*AuthResponse, error)
	mustEmbedUnimplementedAuthGrpcServer()
}

// UnimplementedAuthGrpcServer must be embedded to have forward compatible implementations.
type UnimplementedAuthGrpcServer struct {
}

func (UnimplementedAuthGrpcServer) Validate(context.Context, *TokenPair) (*AuthResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedAuthGrpcServer) mustEmbedUnimplementedAuthGrpcServer() {}

// UnsafeAuthGrpcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthGrpcServer will
// result in compilation errors.
type UnsafeAuthGrpcServer interface {
	mustEmbedUnimplementedAuthGrpcServer()
}

func RegisterAuthGrpcServer(s grpc.ServiceRegistrar, srv AuthGrpcServer) {
	s.RegisterService(&AuthGrpc_ServiceDesc, srv)
}

func _AuthGrpc_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenPair)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGrpcServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/authgrpc.AuthGrpc/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGrpcServer).Validate(ctx, req.(*TokenPair))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthGrpc_ServiceDesc is the grpc.ServiceDesc for AuthGrpc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthGrpc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authgrpc.AuthGrpc",
	HandlerType: (*AuthGrpcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _AuthGrpc_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/mail-service-auth-grpc.proto",
}
